import { Card, CardElement } from './card';

// TODO Create a card manager and load cards from an external JSON file at runtime

/* tslint:disable:max-line-length */
export const Cards: Card[] = [
  { id: 'geezard', values: { top: 1, left: 5, bottom: 1, right: 4 } },
  { id: 'funguar', values: { top: 5, left: 3, bottom: 1, right: 1 } },
  { id: 'bite_bug', values: { top: 1, left: 5, bottom: 3, right: 3 } },
  { id: 'red_bat', values: { top: 6, left: 2, bottom: 1, right: 1 } },
  { id: 'blobra', values: { top: 2, left: 5, bottom: 1, right: 3 } },
  { id: 'gayla', values: { top: 2, left: 4, bottom: 4, right: 1 }, element: CardElement.LIGHTNING },
  { id: 'gesper', values: { top: 1, left: 1, bottom: 4, right: 5 } },
  { id: 'fastitocalon_f', values: { top: 3, left: 1, bottom: 2, right: 5 }, element: CardElement.EARTH },
  { id: 'blood_soul', values: { top: 2, left: 1, bottom: 6, right: 1 } },
  { id: 'caterchipillar', values: { top: 4, left: 3, bottom: 4, right: 2 } },
  { id: 'cockatrice', values: { top: 2, left: 6, bottom: 2, right: 1 }, element: CardElement.LIGHTNING },
  { id: 'grat', values: { top: 7, left: 1, bottom: 3, right: 1 } },
  { id: 'buel', values: { top: 6, left: 3, bottom: 2, right: 2 } },
  { id: 'mesmerize', values: { top: 5, left: 4, bottom: 3, right: 3 } },
  { id: 'glacial_eye', values: { top: 6, left: 3, bottom: 4, right: 1 }, element: CardElement.ICE },
  { id: 'belhelmel', values: { top: 3, left: 3, bottom: 5, right: 4 } },
  { id: 'thrustaevis', values: { top: 5, left: 5, bottom: 2, right: 3 }, element: CardElement.WIND },
  { id: 'anacondaur', values: { top: 5, left: 5, bottom: 3, right: 1 }, element: CardElement.POISON },
  { id: 'creeps', values: { top: 5, left: 2, bottom: 5, right: 2 }, element: CardElement.LIGHTNING },
  { id: 'grendel', values: { top: 4, left: 2, bottom: 5, right: 4 }, element: CardElement.LIGHTNING },
  { id: 'jelleye', values: { top: 3, left: 7, bottom: 1, right: 2 } },
  { id: 'grand_mantis', values: { top: 5, left: 3, bottom: 5, right: 2 } },
  { id: 'forbidden', values: { top: 6, left: 2, bottom: 3, right: 6 } },
  { id: 'armadodo', values: { top: 6, left: 6, bottom: 1, right: 3 }, element: CardElement.EARTH },
  { id: 'tri_face', values: { top: 3, left: 5, bottom: 5, right: 5 }, element: CardElement.POISON },
  { id: 'fastitocalon', values: { top: 7, left: 3, bottom: 1, right: 5 }, element: CardElement.EARTH },
  { id: 'snow_lion', values: { top: 7, left: 3, bottom: 5, right: 1 }, element: CardElement.ICE },
  { id: 'ochu', values: { top: 5, left: 3, bottom: 3, right: 6 } },
  { id: 'sam08g', values: { top: 5, left: 4, bottom: 2, right: 6 }, element: CardElement.FIRE },
  { id: 'death_claw', values: { top: 4, left: 2, bottom: 7, right: 4 }, element: CardElement.FIRE },
  { id: 'cactuar', values: { top: 6, left: 3, bottom: 6, right: 2 } },
  { id: 'tonberry', values: { top: 3, left: 4, bottom: 4, right: 6 } },
  { id: 'abyss_worm', values: { top: 7, left: 5, bottom: 3, right: 2 }, element: CardElement.EARTH },
  { id: 'turtapod', values: { top: 2, left: 7, bottom: 6, right: 3 } },
  { id: 'vysage', values: { top: 6, left: 5, bottom: 4, right: 5 } },
  { id: 't_rexaur', values: { top: 4, left: 7, bottom: 2, right: 6 } },
  { id: 'bomb', values: { top: 2, left: 3, bottom: 6, right: 7 }, element: CardElement.FIRE },
  { id: 'blitz', values: { top: 1, left: 7, bottom: 4, right: 6 }, element: CardElement.LIGHTNING },
  { id: 'wendigo', values: { top: 7, left: 6, bottom: 1, right: 3 } },
  { id: 'torama', values: { top: 7, left: 4, bottom: 4, right: 4 } },
  { id: 'imp', values: { top: 3, left: 6, bottom: 3, right: 7 } },
  { id: 'blue_dragon', values: { top: 6, left: 3, bottom: 7, right: 2 }, element: CardElement.POISON },
  { id: 'adamantoise', values: { top: 4, left: 6, bottom: 5, right: 5 }, element: CardElement.EARTH },
  { id: 'hexadragon', values: { top: 7, left: 3, bottom: 4, right: 5 }, element: CardElement.FIRE },
  { id: 'iron_giant', values: { top: 6, left: 5, bottom: 6, right: 5 } },
  { id: 'behemoth', values: { top: 3, left: 7, bottom: 5, right: 6 } },
  { id: 'chimera', values: { top: 7, left: 3, bottom: 5, right: 6 }, element: CardElement.WATER },
  { id: 'pupu', values: { top: 3, left: 1, bottom: 2, right: 10 } },
  { id: 'elastoid', values: { top: 6, left: 7, bottom: 6, right: 2 } },
  { id: 'gim47n', values: { top: 5, left: 4, bottom: 7, right: 5 } },
  { id: 'malboro', values: { top: 7, left: 2, bottom: 4, right: 7 }, element: CardElement.POISON },
  { id: 'ruby_dragon', values: { top: 7, left: 4, bottom: 7, right: 2 }, element: CardElement.FIRE },
  { id: 'elnoyle', values: { top: 5, left: 6, bottom: 7, right: 3 } },
  { id: 'tonberry_king', values: { top: 4, left: 4, bottom: 7, right: 6 } },
  { id: 'biggs_wedge', values: { top: 6, left: 7, bottom: 2, right: 6 } },
  { id: 'fujin_raijin', values: { top: 2, left: 4, bottom: 8, right: 8 } },
  { id: 'elvoret', values: { top: 7, left: 4, bottom: 3, right: 8 }, element: CardElement.WIND },
  { id: 'x_atm092', values: { top: 4, left: 3, bottom: 7, right: 8 } },
  { id: 'granaldo', values: { top: 7, left: 5, bottom: 8, right: 2 } },
  { id: 'gerogero', values: { top: 1, left: 3, bottom: 8, right: 8 }, element: CardElement.POISON },
  { id: 'iguion', values: { top: 8, left: 2, bottom: 8, right: 2 } },
  { id: 'abadon', values: { top: 6, left: 5, bottom: 4, right: 8 } },
  { id: 'trauma', values: { top: 4, left: 6, bottom: 5, right: 8 } },
  { id: 'oilboyle', values: { top: 1, left: 8, bottom: 4, right: 8 } },
  { id: 'shumi_tribe', values: { top: 6, left: 4, bottom: 8, right: 5 } },
  { id: 'krysta', values: { top: 7, left: 1, bottom: 8, right: 5 } },
  { id: 'propagator', values: { top: 8, left: 8, bottom: 4, right: 4 } },
  { id: 'jumbo_cactuar', values: { top: 8, left: 4, bottom: 4, right: 8 } },
  { id: 'tri_point', values: { top: 8, left: 8, bottom: 2, right: 5 }, element: CardElement.LIGHTNING },
  { id: 'gargantua', values: { top: 5, left: 8, bottom: 6, right: 6 } },
  { id: 'mobile_type_8', values: { top: 8, left: 3, bottom: 7, right: 6 } },
  { id: 'sphinxara', values: { top: 8, left: 8, bottom: 5, right: 3 } },
  { id: 'tiamat', values: { top: 8, left: 4, bottom: 5, right: 8 } },
  { id: 'bgh251f2', values: { top: 5, left: 5, bottom: 8, right: 7 } },
  { id: 'red_giant', values: { top: 6, left: 7, bottom: 4, right: 8 } },
  { id: 'catoblepas', values: { top: 1, left: 7, bottom: 7, right: 8 } },
  { id: 'ultima_weapon', values: { top: 7, left: 8, bottom: 2, right: 7 } },
  { id: 'chubby_chocobo', values: { top: 4, left: 9, bottom: 8, right: 4 } },
  { id: 'angelo', values: { top: 9, left: 3, bottom: 7, right: 6 } },
  { id: 'gilgamesh', values: { top: 3, left: 6, bottom: 9, right: 7 } },
  { id: 'mini_mog', values: { top: 9, left: 2, bottom: 9, right: 3 } },
  { id: 'chicobo', values: { top: 9, left: 4, bottom: 8, right: 4 } },
  { id: 'quezacotl', values: { top: 2, left: 4, bottom: 9, right: 9 }, element: CardElement.LIGHTNING },
  { id: 'shiva', values: { top: 6, left: 9, bottom: 4, right: 7 }, element: CardElement.ICE },
  { id: 'ifrit', values: { top: 9, left: 8, bottom: 2, right: 6 }, element: CardElement.FIRE },
  { id: 'siren', values: { top: 8, left: 2, bottom: 6, right: 9 } },
  { id: 'sacred', values: { top: 5, left: 9, bottom: 9, right: 1 } },
  { id: 'minotaur', values: { top: 9, left: 9, bottom: 2, right: 5 } },
  { id: 'carbuncle', values: { top: 8, left: 4, bottom: 10, right: 4 } },
  { id: 'diablos', values: { top: 5, left: 3, bottom: 8, right: 10 } },
  { id: 'leviathan', values: { top: 7, left: 7, bottom: 1, right: 10 }, element: CardElement.WATER },
  { id: 'odin', values: { top: 8, left: 5, bottom: 3, right: 10 } },
  { id: 'pandemona', values: { top: 10, left: 7, bottom: 7, right: 1 }, element: CardElement.WIND },
  { id: 'cerberus', values: { top: 7, left: 10, bottom: 6, right: 4 } },
  { id: 'alexander', values: { top: 9, left: 2, bottom: 4, right: 10 }, element: CardElement.HOLY },
  { id: 'phoenix', values: { top: 7, left: 10, bottom: 7, right: 2 }, element: CardElement.FIRE },
  { id: 'bahamut', values: { top: 10, left: 6, bottom: 2, right: 8 } },
  { id: 'doomtrain', values: { top: 3, left: 10, bottom: 10, right: 1 }, element: CardElement.POISON },
  { id: 'eden', values: { top: 4, left: 10, bottom: 9, right: 4 } },
  { id: 'ward', values: { top: 10, left: 8, bottom: 2, right: 7 } },
  { id: 'kiros', values: { top: 6, left: 10, bottom: 6, right: 7 } },
  { id: 'laguna', values: { top: 5, left: 9, bottom: 3, right: 10 } },
  { id: 'selphie', values: { top: 10, left: 4, bottom: 6, right: 8 } },
  { id: 'quistis', values: { top: 9, left: 2, bottom: 10, right: 6 } },
  { id: 'irvine', values: { top: 2, left: 10, bottom: 9, right: 6 } },
  { id: 'zell', values: { top: 8, left: 6, bottom: 10, right: 5 } },
  { id: 'rinoa', values: { top: 4, left: 10, bottom: 2, right: 10 } },
  { id: 'edea', values: { top: 10, left: 3, bottom: 3, right: 10 } },
  { id: 'seifer', values: { top: 6, left: 4, bottom: 10, right: 9 } },
  { id: 'squall', values: { top: 10, left: 9, bottom: 6, right: 4 } },
];
/* tslint:enable:max-line-length */

export const CardsMap = new Map<string, Card>(
  Cards.map(c => [c.id, c] as [string, Card])
);
